title: Greetings from Alina
description: "Personal space for tracking progress in time. How can Data Science help in answering questions?"
social_media_share_image: /images/avatar.jpg
disqus-identifier:
google-analytics:
