# Tools
apps script:
  en: Apps Script
  ru: Apps Script
  type: tool

api:
  en: API
  ru: API
  type: tool

appsheet:
  en: AppSheet
  ru: AppSheet
  type: tool

flowchart:
  en: Flowchart
  ru: Блок-схема
  type: tool

google sheets:
  en: Google Sheets
  ru: Google Таблицы
  type: tool

excel:
  en: Excel
  ru: Excel
  type: tool

notion:
  en: Notion
  ru: Notion
  type: tool

obsidian:
  en: Obsidian
  ru: Obsidian
  type: tool

pivot:
  en: Pivot
  ru: Сводные таблицы
  type: tool

power bi:
  en: Power BI
  ru: Power BI
  type: tool

power query:
  en: Power Query
  ru: Power Query
  type: tool

tool-python:
  en: Python
  ru: Python
  type: tool

pdfplumber:
  en: pdfplumber
  ru: pdfplumber
  type: tool

pandas:
  en: pandas
  ru: pandas
  type: tool

tableau:
  en: Tableau
  ru: Tableau
  type: tool

tbl script:
  en: TBL script
  ru: TBL script
  type: tool

tool-sql:
  en: SQL
  ru: SQL
  type: tool

vba:
  en: VBA
  ru: VBA
  type: tool

datalens:
  en: DataLens
  ru: DataLens
  type: tool

# Categories

automation:
  en: automation
  ru: автоматизация
  type: category

bi-analytics:
  en: BI-analytics
  ru: BI-аналитика
  type: category

chatbot:
  en: chatbot
  ru: чат-бот
  type: category

dashboard:
  en: dashboard
  ru: dashboard
  type: category

data-viz:
  en: data-viz
  ru: визуализация
  type: category

db:
  en: DB
  ru: БД
  type: category

etl:
  en: ETL
  ru: ETL
  type: category

finance:
  en: finance
  ru: финансы
  type: category

helper:
  en: helper
  ru: помощник
  type: category

process:
  en: process
  ru: бизнес-процесс
  type: category

# POSTS
ai:
  en: AI
  ru: ИИ

data:
  en: data
  ru: данные

math:
  en: Math
  ru: математика

ml:
  en: ML
  ru: машинное-обучение

musings:
  en: musings
  ru: размышления

planning:
  en: planning
  ru: планы

python:
  en: Python
  ru: Python

quick-ref:
  en: quick-ref
  ru: памятки

sql:
  en: SQL
  ru: SQL

web-dev:
  en: web-dev
  ru: веб-разработка

writing:
  en: writing
  ru: письмо
