# Tools
apps script:
  en: Apps Script
  ru: Apps Script
  type: tool

api:
  en: API
  ru: API
  type: tool

appsheet:
  en: AppSheet
  ru: AppSheet
  type: tool

google sheets:
  en: Google Sheets
  ru: Google Таблицы
  type: tool

excel:
  en: Excel
  ru: Excel
  type: tool

notion:
  en: Notion
  ru: Notion
  type: tool

obsidian:
  en: Obsidian
  ru: Obsidian
  type: tool

pivot:
  en: Pivot
  ru: Сводные таблицы
  type: tool

power bi:
  en: Power BI
  ru: Power BI
  type: tool

power query:
  en: Power Query
  ru: Power Query
  type: tool

python:
  en: Python
  ru: Python
  type: tool

sql:
  en: SQL
  ru: SQL
  type: tool

vba:
  en: VBA
  ru: VBA
  type: tool

datalens:
  en: DataLens
  ru: DataLens
  type: tool

# Categories
analysis:
  en: analysis
  ru: анализ
  type: category

automation:
  en: automation
  ru: автоматизация
  type: category

chatbot:
  en: chatbot
  ru: чат-бот
  type: category

db:
  en: DB
  ru: БД
  type: category

diagrams:
  en: diagrams
  ru: диаграммы
  type: category

helper:
  en: helper
  ru: помощник
  type: category

visuals:
  en: visuals
  ru: визуализация
  type: category
