# Tools
apps script:
  ru: Apps Script
  en: Apps Script
  type: tool

api:
  ru: API
  en: API
  type: tool

appsheet:
  ru: AppSheet
  en: AppSheet
  type: tool

flowchart:
  ru: Блок-схема
  en: Flowchart
  type: tool

google sheets:
  ru: Google Таблицы
  en: Google Sheets
  type: tool

excel:
  en: Excel
  ru: Excel
  type: tool

notion:
  ru: Notion
  en: Notion
  type: tool

obsidian:
  ru: Obsidian
  en: Obsidian
  type: tool

pivot:
  ru: Сводные таблицы
  en: Pivot
  type: tool

power bi:
  ru: Power BI
  en: Power BI
  type: tool

power query:
  ru: Power Query
  en: Power Query
  type: tool

tool-python:
  ru: Python
  en: Python
  type: tool

pdfplumber:
  ru: pdfplumber
  en: pdfplumber
  type: tool

pandas:
  ru: pandas
  en: pandas
  type: tool

tableau:
  ru: Tableau
  en: Tableau
  type: tool

tbl script:
  ru: TBL script
  en: TBL script
  type: tool

tool-sql:
  ru: SQL
  en: SQL
  type: tool

vba:
  ru: VBA
  en: VBA
  type: tool

datalens:
  ru: DataLens
  en: DataLens
  type: tool

# Categories

automation:
  ru: автоматизация
  en: automation
  type: category

bi-analytics:
  ru: BI-аналитика
  en: BI-analytics
  type: category

chatbot:
  ru: чат-бот
  en: chatbot
  type: category

dashboard:
  ru: dashboard
  en: dashboard
  type: category

data-viz:
  ru: визуализация
  en: data-viz
  type: category

db:
  ru: БД
  en: DB
  type: category

etl:
  ru: ETL
  en: ETL
  type: category

finance:
  ru: финансы
  en: finance
  type: category

helper:
  ru: помощник
  en: helper
  type: category

process:
  ru: бизнес-процесс
  en: process
  type: category

# POSTS
ai:
  ru: ИИ
  en: AI
  type: category

data:
  ru: данные
  en: data
  type: category

math:
  ru: математика
  en: Math
  type: category

ml:
  ru: машинное-обучение
  en: ML
  type: tool

musings:
  ru: размышления
  en: musings
  type: category

planning:
  ru: планы
  en: planning
  type: category

python:
  ru: Python
  en: Python
  type: tool

quick-ref:
  ru: памятки
  en: quick-ref
  type: category

sql:
  ru: SQL
  en: SQL
  type: tool

web-dev:
  ru: веб-разработка
  en: web-dev
  type: category

writing:
  ru: письмо
  en: writing
  type: category
